feat:add codesandox template
chakra-ui/vue-docs pull request #29
Opened 2023-04-29 20:07 UTC by D-Lite

Addition of a codesandbox template to the documentation.

![cs](https://user-images.githubusercontent.com/44473671/235322255-aa0a7e45-1ed8-4841-a422-0ec00b6041f2.png)

2023-05-05 10:35 UTC, carwack commented on content/1.getting-started/0.index.md
> +<iframe src="https://codesandbox.io/embed/vue-chakra-next-with-autoimport-r1shkt?fontsize=14&hidenavigation=1&theme=dark&view=preview&codemirror=1&highlights=6,7,8,9"
Looks nice!
Is it also possible to have some fall back option like just the URL in case CSB doesn't load correctly?

2023-05-05 10:42 UTC, D-Lite commented on content/1.getting-started/0.index.md
> +<iframe src="https://codesandbox.io/embed/vue-chakra-next-with-autoimport-r1shkt?fontsize=14&hidenavigation=1&theme=dark&view=preview&codemirror=1&highlights=6,7,8,9"
Yes, I can add the fallback URL incase it does not load correctly.

2023-05-12 21:04 UTC, codebender828 requested changes

2023-05-12 21:04 UTC, codebender828 commented on content/1.getting-started/0.index.md
> +<iframe src="https://codesandbox.io/embed/vue-chakra-next-with-autoimport-r1shkt?fontsize=14&hidenavigation=1&theme=dark&view=preview&codemirror=1&highlights=6,7,8,9"
Nice the starter is working well for this one. Do you think we can render the codesandbox the same way motion.dev renders theirs on their site?

https://motion.dev/vue/quick-start

<img width="1017" alt="CleanShot 2023-05-13 at 05 02 08@2x" src="https://github.com/chakra-ui/vue-docs/assets/21237954/eacbb9ca-9ab7-4ccd-8ce1-1dc5b7761a61">

Also would be nice to add something to the starter. Right now it's a little empty. Maybe a few buttons or widgets.

2023-05-14 13:54 UTC, D-Lite commented
@codebender828 I tried recreating the motion.dev structure as much as I can, now in a split mode. 

I think it might be good leaving the codesandbox minimal at the moment, as this is just a starter file for people. Regardless, I can add more things to the starter.

2023-05-20 09:15 UTC, jbakebwa approved these changes

2023-05-20 09:26 UTC, codebender828 approved these changes

2023-05-20 09:26 UTC, codebender828 commented
Thank you,.

2023-05-20 09:26 UTC, merged